# Sample .travis.yml for R projects

language: r
matrix:
  include:
    - os: linux
      dist: precise

sudo: false
cache: packages
r:
  - release
  - devel



warnings_are_errors: true

r_github_packages:
  - jimhester/covr



after_success:
  - Rscript -e 'library(covr);codecov()'
